name: Publish Docker Images

on:
  push:
    branches: ["main"]
    tags: ["*"]

  pull_request:
    branches: ["main"]

# Kill existing jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mill1000/snapcast-server

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        platform: [linux/amd64] #linux/arm/v7,linux/arm64,

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # Generate tags for latest commit, version tags and PRs
          tags: |
            type=edge
            type=pep440,pattern={{version}}
            type=ref,event=pr

      - uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.platform }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
